[workspace]

members = [
    "riichi",
    "riichi-elements",
    "riichi-decomp-table",
    "tenhou-db"
]


[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }
phf_codegen = { version = "0.11" }
