[package]
name = "riichi-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]

anyhow = { workspace = true }
polars = "0.46.0"

serde = { workspace = true }
serde_json = { workspace = true }

riichi = { path = "../riichi", version = "0.1.0" }